// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Report$TssUi from "./components/Report/Report.bs.js";
import * as Realtime$TssUi from "./components/Realtime/Realtime.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function Container(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var show = match ? (
      match[0] === "report" ? (
          match[1] ? React.createElement(Realtime$TssUi.make, { }) : React.createElement(Report$TssUi.make, { })
        ) : React.createElement(Realtime$TssUi.make, { })
    ) : React.createElement(Realtime$TssUi.make, { });
  return React.createElement("div", {
              className: "container tss-Container"
            }, show);
}

var make = Container;

export {
  make ,
  
}
/* react Not a pure module */
